In [1]:
import pandas as pd
import numpy as np
import math


In [2]:
data1=pd.read_csv('./datasets/ProcessedData/encodedTargets1.csv')
data2=pd.read_csv('./datasets/ProcessedData/encodedTargets2.csv')
data3=pd.read_csv('./datasets/ProcessedData/encodedTargets3.csv')
data4=pd.read_csv('./datasets/ProcessedData/encodedTargets4.csv')
data5=pd.read_csv('./datasets/ProcessedData/encodedTargets5.csv')
data6=pd.read_csv('./datasets/ProcessedData/encodedTargets6.csv')
data7=pd.read_csv('./datasets/ProcessedData/encodedTargets7.csv')
data8=pd.read_csv('./datasets/ProcessedData/encodedTargets8.csv')
data9=pd.read_csv('./datasets/ProcessedData/encodedTargets9.csv')


In [3]:
data = pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9], axis=0)
len(data) #1087273 expected

1087273

In [4]:
data.head()

Condition  yellowing_of_eyes  spasm  \
0  Peripheral Nervous System Diseases                  0      0   
1                        Hypertension                  0      0   
2               Toxoplasmosis, Animal                  0      0   
3                 Prostatic Neoplasms                  0      0   
4           Epilepsy;Vision Disorders                  0      0   

   Muscular Atrophy  Chills  homelessness  para 2  Athetosis  gag  \
0                 0       0             0       0          0    0   
1                 0       0             0       0          0    0   
2                 0       0             0       0          0    0   
3                 0       0             0       0          0    0   
4                 0       0             0       0          0    0   

   avoid too many products  ...  get away from trigger  hypertonicity  \
0                        0  ...                      0              0   
1                        0  ...                      0              0   
2                        0  ...                      0              0   
3                        0  ...                      0              0   
4                        0  ...                      0              0   

   systolic murmur  Pupil Disorders  Overweight  Stahli's line  \
0                0                0           0              0   
1                0                0           0              0   
2                0                0           0              0   
3                0                0           0              0   
4                0                0           0              0   

   Body Weight Changes  symptom aggravating factors  hypersomnolence  Target  
0                    0                            0                0       0  
1                    0                            0                0       1  
2                    0                            0                0       2  
3                    0                            0                0       3  
4                    0                            0                0       4  

[5 rows x 811 columns]

In [5]:
data = data.drop(['Condition'], axis=1)

In [6]:
data.head()

yellowing_of_eyes  spasm  Muscular Atrophy  Chills  homelessness  para 2  \
0                  0      0                 0       0             0       0   
1                  0      0                 0       0             0       0   
2                  0      0                 0       0             0       0   
3                  0      0                 0       0             0       0   
4                  0      0                 0       0             0       0   

   Athetosis  gag  avoid too many products  prostatism  ...  \
0          0    0                        0           0  ...   
1          0    0                        0           0  ...   
2          0    0                        0           0  ...   
3          0    0                        0           0  ...   
4          0    0                        0           0  ...   

   get away from trigger  hypertonicity  systolic murmur  Pupil Disorders  \
0                      0              0                0                0   
1                      0              0                0                0   
2                      0              0                0                0   
3                      0              0                0                0   
4                      0              0                0                0   

   Overweight  Stahli's line  Body Weight Changes  \
0           0              0                    0   
1           0              0                    0   
2           0              0                    0   
3           0              0                    0   
4           0              0                    0   

   symptom aggravating factors  hypersomnolence  Target  
0                            0                0       0  
1                            0                0       1  
2                            0                0       2  
3                            0                0       3  
4                            0                0       4  

[5 rows x 810 columns]

In [8]:
len(data)

1087273

In [9]:
test = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
testdf = pd.DataFrame(test, columns = ['a','b','c'])
testarray = testdf.to_numpy()

In [10]:
print(testarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
np.random.shuffle(testarray)


In [12]:
print(testarray)

[[ 4  5  6]
 [10 11 12]
 [ 7  8  9]
 [ 1  2  3]]


In [13]:
dataArray = data.to_numpy()
metric = data.to_numpy()

In [14]:
np.random.shuffle(dataArray)
#halt

In [15]:
dataArray[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [16]:
x = []
y = []
l = len(dataArray[0])
for z in range(len(dataArray)):
    x.append(dataArray[z][:l-1])
    y.append(dataArray[z][l-1])

In [17]:
len(x)

1087273

In [18]:
len(dataArray)

1087273

In [19]:
len(y)

1087273

In [ ]:
import csv

In [ ]:
with open('./datasets/ProcessedData/FinalEncodedDataX.csv', 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     wr.writerow(x)

In [ ]:
with open('./datasets/ProcessedData/FinalEncodedDataY.csv', 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     wr.writerow(Y)

In [ ]:
'''te = [1,2,3,4,5,6,7,8,9,10]
print(te[:2])
print(te[2:])'''

In [ ]:
x_train = np.array(x[:975000])
y_train = np.array(y[:975000])





In [ ]:
x_validation = np.array(x[975000:])
y_validation = np.array(y[975000:])

In [20]:
x_timetest = np.array(x[:10000])
y_timetest = np.array(y[:10000])

In [21]:
type(x_timetest)

numpy.ndarray

In [ ]:
#testing data

In [22]:
import tensorflow as tf
    
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(4255, activation=tf.nn.softmax))
          
model.compile(optimizer='adam' , loss='sparse_categorical_crossentropy',metrics=['accuracy'])
          
model.fit(x_timetest, y_timetest, batch_size=32, epochs = 4)


Epoch 1/4
313/313 [==============================] - 5s 13ms/step - loss: 7.2113 - accuracy: 0.0925
Epoch 2/4
313/313 [==============================] - 4s 13ms/step - loss: 5.7123 - accuracy: 0.1707
Epoch 3/4
313/313 [==============================] - 4s 12ms/step - loss: 4.9601 - accuracy: 0.2697
Epoch 4/4
313/313 [==============================] - 4s 14ms/step - loss: 4.4537 - accuracy: 0.3138


In [23]:
val_loss, val_acc = model.evaluate(x_timetest,y_timetest)
print(val_loss, val_acc)

313/313 [==============================] - 3s 8ms/step - loss: 4.1267 - accuracy: 0.3446
4.126716613769531 0.34459999203681946


In [24]:
model.save('model_1.model')

INFO:tensorflow:Assets written to: model_1.model\assets


In [25]:
new_model = tf.keras.models.load_model('model_1.model')

In [53]:
'''test = [0]*809
test[230] = 1
test[233] = 1
test[566] = 1
test[283] = 1
test[195] = 1
test[405] = 1
test[56] = 1
'''

test = [0]*809
test[326] = 1
test[363] = 1

In [54]:
predictions = new_model.predict([test])

In [55]:
print(predictions[0])

[9.9266483e-04 3.6378440e-02 2.5045173e-07 ... 5.4752518e-06 1.3080171e-05
 7.8853554e-05]


In [56]:
print(np.argmax(predictions[0]))

13


In [27]:
conditions=pd.read_csv('../datasets/ProcessedData/Conditions.csv')


In [28]:
conditions.head()

Condition
0  Peripheral Nervous System Diseases
1                        Hypertension
2               Toxoplasmosis, Animal
3                 Prostatic Neoplasms
4           Epilepsy;Vision Disorders

In [29]:
conditions = conditions['Condition'].to_list()

In [34]:
len(conditions)

4264

In [58]:
np.sort(predictions[0])


array([4.1445407e-08, 4.7136282e-08, 7.9518095e-08, ..., 2.5907699e-02,
       3.6378440e-02, 1.2451359e-01], dtype=float32)

In [59]:
np.argsort(predictions[0])


array([ 480, 1227, 3907, ...,  278,    1,   13], dtype=int64)

In [48]:
symptoms = pd.read_csv('./datasets/ProcessedData/Symptoms.csv')
symptoms.head()

0
0  yellowing_of_eyes
1              spasm
2   Muscular Atrophy
3             Chills
4       homelessness

In [49]:
symptoms = symptoms['0'].to_list()


In [52]:
symptoms.index('Drug effect')

363